/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xh_image_Image */

#ifndef _Included_com_xh_image_Image
#define _Included_com_xh_image_Image
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_xh_image_Image
	* Method:    test
	* Signature: ([Ljava/lang/String;)I
	*/
	JNIEXPORT jint JNICALL Java_com_xh_image_Image_test
	(JNIEnv *, jclass, jobjectArray);

	/*
	* Class:     com_xh_image_Image
	* Method:    rotate270
	* Signature: ([II)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_rotate270
	(JNIEnv *, jclass, jintArray, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    rotate90
	* Signature: ([II)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_rotate90
	(JNIEnv *, jclass, jintArray, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    look_mirror
	* Signature: ([II)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_look_1mirror
	(JNIEnv *, jclass, jintArray, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    rotate180
	* Signature: ([II)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_rotate180
	(JNIEnv *, jclass, jintArray, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    interception
	* Signature: ([IIIIII)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_interception
	(JNIEnv *, jclass, jintArray, jint, jint, jint, jint, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    look_mirrorX
	* Signature: ([II)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_look_mirrorX
	(JNIEnv *, jclass, jintArray, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    nostalgia
	* Signature: ([II)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_nostalgia
	(JNIEnv *, jclass, jintArray, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    relief
	* Signature: ([II)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_relief
	(JNIEnv *, jclass, jintArray, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    fuzzy
	* Signature: ([II)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_fuzzy
	(JNIEnv *, jclass, jintArray, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    sunshine
	* Signature: ([IIII)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_sunshine
	(JNIEnv *, jclass, jintArray, jint, jint, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    sharpen
	* Signature: ([II)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_sharpen
	(JNIEnv *, jclass, jintArray, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    ice
	* Signature: ([II)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_ice
	(JNIEnv *, jclass, jintArray, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    sketch
	* Signature: ([II)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_sketch
	(JNIEnv *, jclass, jintArray, jint);

	/*
	* Class:     com_xh_image_Image
	* Method:    addFrameToImageTwo
	* Signature: ([II[II)[I
	*/
	JNIEXPORT jintArray JNICALL Java_com_xh_image_Image_addFrameToImageTwo
	(JNIEnv *, jclass, jintArray, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
